### ISSUE TITLE
Kaufen im Shop möglich?

### ISSUE THREAD

**Issue by kkuez** [DEVTomatoCake/TomatenKuchen-i18n#9]
Hi, 
Wir haben heute euren Bot auf den Server geholt. Ist es schon möglich Dinge im Shop zu kaufen?

**Comment by DEVTomatoCake** [comment]
Nein, das Economy-System ist noch komplett in Arbeit und vorallem der Shop wird noch komplett überarbeitet.
Würde dir außerdem empfehlen, für solche Fragen entweder dem [Support-Discord](https://discord.gg/ZqzFUC8qe9) zu joinen oder dem Bot eine PN zu schreiben, da können wir einfacher helfen.
